language: ruby
rvm:
  - 2.2.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql
  - sudo apt-get install -qq postgresql-server-dev-9.3
  - sudo apt-get install -qq libpq-dev
